name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Compress assets
        run: |
          npm install -g imagemin-cli imagemin-mozjpeg imagemin-pngquant
          npx imagemin assets/images/* --plugin=pngquant --plugin=mozjpeg --out-dir=assets/images
      
      - name: Build web (optimized)
        run: flutter build web --release --base-href /MyPortfolio/

      # ğŸ”¹ Ø¶ØºØ· Ø§Ù„ØµÙˆØ± ÙˆØªØ­ÙˆÙŠÙ„Ù‡Ø§ Ù„Ù€ WebP
      - name: Optimize images
        run: |
          sudo apt-get update
          sudo apt-get install -y webp
          find build/web/assets -type f \( -name '*.png' -o -name '*.jpg' -o -name '*.jpeg' \) -exec cwebp -q 80 {} -o {}.webp \;
          find build/web/assets -type f \( -name '*.png' -o -name '*.jpg' -o -name '*.jpeg' \) -exec rm {} \;

      # ğŸ”¹ Ø¶ØºØ· Ù…Ù„ÙØ§Øª HTML, CSS, JS
      - name: Optimize assets (HTML, CSS, JS)
        run: |
          sudo apt-get install -y brotli
          find build/web -type f \( -name '*.js' -o -name '*.css' -o -name '*.html' \) -exec gzip -9 -k {} \;
          find build/web -type f \( -name '*.js' -o -name '*.css' -o -name '*.html' \) -exec brotli -9 {} \;

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
